namespace: store
deployment:
  replicas: 1
  imageName: devopsrinu/frontend
  imageVersion: v1

hpa:
  minReplicas: 1
  maxReplicas: 3
  averageUtilization: 10

service:
  targetPort: 80
  port: 80


