namespace: store
deployment:
  replicas: 1
  imageName: devopsrinu/cart-service
  imageVersion: v1

hpa:
  minReplicas: 1
  maxReplicas: 2
  averageUtilization: 80

service:
  targetPort: 8083
  port: 8083

