namespace: store
deployment:
  replicas: 1
  imageName: 597819998113.dkr.ecr.us-east-1.amazonaws.com/flower-store/order-service
  imageVersion: v1

hpa:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 85

service:
  targetPort: 8084
  port: 8084

