namespace: store
deployment:
  replicas: 1
  imageName: 597819998113.dkr.ecr.us-east-1.amazonaws.com/flower-store/feedback-service
  imageVersion: IMAGE_VERSION

hpa:
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 80

service:
  targetPort: 8085
  port: 8085

