namespace: store
deployment:
  replicas: 1
  imageName: devopsrinu/api-gateway
  imageVersion: v1

hpa:
  minReplicas: 1
  maxReplicas: 3
  averageUtilization: 70

service:
  targetPort: 8085
  port: 8085

