apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
  labels:
    project: online-store
    component: product-service
spec:
  selector:
    project: online-store
    component: product-service
  ports:
    - protocol: TCP
      port:  {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}