apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    project: online-store
    component: frontend
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      project: online-store
      component: frontend
  template:
    metadata:
      labels:
        project: online-store
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: Always
        ports:
          - containerPort:  {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: 100m
            memory: "128Mi"